stage2_base_config: configs/stage2_roleproto.yaml

downstream_proto_train:
  seed: 42
  ckpt_dir: downstream_checkpoints/camelyon_learnable_role_proto_v1

  # stage2 best model 输出的静态 proto，作为初始化
  role_proto_dir: outputs/role_proto_init_virchow2_layer26_405/3role_v1

  # CAMELYON17 bag-level dataset
  train_csv_path: ../data/CAMELYON17/stage2_wsi_train.csv
  val_csv_path: ../data/CAMELYON17/stage2_wsi_val.csv
  raw_dir: ../data/CAMELYON17/images
  h5_dir: ../data/CAMELYON17/patches/patches

  patch_size: 256
  read_level: 0
  resize_to: 224
  max_patches: 64
  sample_mode: random
  check_files: true
  num_workers: 4

  # model behavior
  use_last_moe_output: true
  tumor_role_name: tumor
  role_temperature: 0.07

  # first version: 先只学 proto，不学 proj
  learn_proj: false

  # bag pooling
  bag_topk_ratio: 0.10
  bag_topk_min: 4
  bag_topk_max: 16

  # first version: 先不开额外 tumor margin aux
  tumor_margin_loss_weight: 0.0

  # optimization
  epochs: 10
  patch_batch_size: 16
  lr_proto: 1.0e-3
  lr_proj: 1.0e-4
  lr_bag: 1.0e-3
  weight_decay: 1.0e-4

  early_stop_patience: 5
  early_stop_min_delta: 1.0e-4